# SAE 2.02 - Exploitation algorithmique d'un problème

In [26]:
from numpy.random import randint 
import numpy as np
from math import sqrt
import matplotlib.pyplot as plt

def norme(X) :
    return np.sqrt(np.sum(X**2))

A = np.array([
 [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]],dtype = float)

def creeMatriceAleatoire (i):
    return np.random.rand(i);

def puissanceIteree (A,e,Xo) :
    Xn = Xo.copy()
    XnOld = np.zeros(len(A))
    if (estStochastique(A)) :
        while (norme(Xn - XnOld) > e) :
            XnOld = Xn.copy()
            AXn = A.dot(Xn)
            Xn = AXn.copy()
        return Xn
    else :
        while (norme(Xn - XnOld) > e) :
            XnOld = Xn.copy()
            AXn = A.dot(Xn)
            Xn = AXn / norme(AXn)
        return Xn

def stochastique(A) :
    for i in range (A.shape[0]):
        temp = 0
        for j in range (A.shape[0]) :
            if (A[j][i] == 1) :
                temp += 1
        for k in range (A.shape[0]) :
            if (A[k][i] == 1) :
                A[k][i] /= temp
    return A

def estStochastique(A) :
    for i in range (A.shape[0]):
        temp = 0
        for j in range (A.shape[0]) :
            temp += A[j][i]
        if (temp != 1):
            return False
    return True

def transposee(A) :
    return A.T


def solutionEquation(V,W) :
    return norme(V - W)

# r est notre vecteur retourné dans l'algorithme ci-dessus
def verification(Q,e) : 
    r = puissanceIteree(Q,e,Xo)
    # r est notre vecteur retourné dans l'algorithme ci-dessus
    R = solutionEquation(r, Q.dot(r))
    #R va nous afficher l'écart (sensé tendre vers le nul) entre r et Q*r
    if (R > 1e-5):     #ici, 1e-5 est la marge d'erreur
        return "le vecteur retourné n'est pas solution de l'équation : r = Qr", R
    else : 
        return "le vecteur retourné est solution de l'équation : la norme de r = Qr = ", R

Xo = creeMatriceAleatoire(len(A))

Q = (stochastique(transposee(A)))
print(Q)
e = 10**(-10)
print (puissanceIteree (Q,e,Xo))
print (verification(Q,e))

[[0.         0.5        0.5        0.5        0.5        0.
  0.5        0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.5        0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.5        0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.         0.5        0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.5        0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.         0.         0.
  0.         1.         0.         0.2        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.33333333
  0.         0.         0.         0.         0.         0.
  

## Partie 2 : PageRank - version itérative, deuxième exemple

In [19]:
#B est le graphe d'ordre 5.
B = np.array([
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 1, 0],
 [1, 1, 0, 0, 0],
 [1, 1, 0, 0, 0]], dtype = float)

Q = (transposee(B))

Xo = creeMatriceAleatoire(len(B))

print(Q)
print('\n')
print(puissanceIteree(Q, e,Xo))

[[0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


[nan nan nan nan nan]


/tmp/ipykernel_22043/1837178621.py:41: RuntimeWarning: invalid value encountered in divide
  Xn = AXn / norme(AXn)


In [23]:
#Question 2

def matriceTransition(A,B,a) :
    M = np.zeros((len(A),len(A)))
    for i in range (len(A)):
        for j in range (len(A)) :
            if (sommeTableau(j,A) != 0):    
                M[i][j] = a*B[i][j] + (1-a)/len(A)
            else:
                M[i][j] = 1/len(A)
    return M       

def sommeTableau(j,A) :
    temp = 0
    for i in range (A.shape[0]):
        temp += A[i][j]
    return (temp)

a = 0.85
Xo = creeMatriceAleatoire(len(B))
P = matriceTransition(transposee(B),stochastique(transposee(B)),a)
print (P,"\n\n")
print (puissanceIteree(P,e,Xo),"\n")
print(verification(P,e))

[[0.2   0.88  0.455 0.455 0.455]
 [0.2   0.03  0.03  0.455 0.455]
 [0.2   0.03  0.03  0.03  0.03 ]
 [0.2   0.03  0.455 0.03  0.03 ]
 [0.2   0.03  0.03  0.03  0.03 ]] 


[1.58831164 0.77128897 0.37982836 0.54125541 0.37982836] 

("le vecteur retourné n'est pas solution de l'équation : r = Qr", 6.592593548076076)


## Partie 3 : PageRank - version itérative, analyse des paramètres

In [27]:

def equation(Q,e) : 
    r = puissanceIteree(Q,e,Xo)
    # r est notre vecteur retourné dans l'algorithme ci-dessus
    return solutionEquation(r, Q.dot(r))

Xo = creeMatriceAleatoire(len(A))

Q = (stochastique(transposee(A)))

e = 1
print("e = ", e, " : ",equation (Q,e),"\n")
e = 1e-2
print("e = ", e, " : ",equation (Q,e),"\n")
e= 1e-4
print("e = ", e, " : ",equation(Q,e),"\n")
e = 1e-6
print("e = ", e, " : ",equation(Q,e),"\n")
e = 1e-8
print("e = ", e, " : ",equation(Q,e),"\n")
e = 1e-10
print("e = ", e, " : ",equation(Q,e),"\n")
e = 1e-20
print("e = ", e, " : ",equation(Q,e),"\n")
e = 1e-100
print("e = ", e, " : ",equation(Q,e),"\n")


e =  1  :  0.533444271088731 

e =  0.01  :  0.005832179882451736 

e =  0.0001  :  9.068869106210485e-05 

e =  1e-06  :  8.763128594556156e-07 

e =  1e-08  :  9.1043295743633e-09 

e =  1e-10  :  8.797397332267904e-11 

e =  1e-20  :  0.0 

e =  1e-100  :  0.0 



In [13]:
#Question 2

#on va ajouter des pages supplémentaires par rapport au nombre de hubs et d'autorités voulu

    #ajout de d'1 hub pointé par aucune page 

H1 = np.array([
     [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]]
         ,dtype=float)

    #ajout de 2 hubs pointés par aucune page 
    
H2 = np.array([
     [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]]
         ,dtype = float)

    #ajout de 2 hubs pointés par aucune page, mais ne pointant pas 8

H3 = np.array([
     [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0]]
         ,dtype = float)

    #ajout d'une autoritée ne pointant aucune page 

A1 = np.array([
     [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
             ,dtype = float)
    
    #ajout de 2 autorités ne pointant aucune page 

A2 = np.array([
     [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
     [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
     [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
     [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
     [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
     [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1],
     [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
    
         ,dtype=float)
    
    
M = matriceTransition(transposee(A),stochastique(transposee(A)),a)
MH1 = matriceTransition(transposee(H1),stochastique(transposee(H1)),a)
MH2 = matriceTransition(transposee(H2),stochastique(transposee(H2)),a)
MH3 = matriceTransition(transposee(H3),stochastique(transposee(H3)),a)
MA1 = matriceTransition(transposee(A1),stochastique(transposee(A1)),a)
MA2 = matriceTransition(transposee(A2),stochastique(transposee(A2)),a)
    
Xo = creeMatriceAleatoire(14)
print("\nPour une matrice sans hub ni autorité :\n")
print (puissanceIteree (M,e,Xo))
    
Xo = creeMatriceAleatoire(15)
print("\nEn ajoutant un hub pointé par aucune page :\n")
print (puissanceIteree (MH1,e,Xo))
    
Xo = creeMatriceAleatoire(16)
print("\nEn ajoutant 2 hubs pointés par aucune page :\n")
print (puissanceIteree (MH2,e,Xo))

Xo = creeMatriceAleatoire(16)
print("\nEn ajoutant 2 hubs pointés par aucune page mais ne pointant pas 8:\n")
print (puissanceIteree (MH3,e,Xo))
    
Xo = creeMatriceAleatoire(15)
print("\nEn ajoutant une autorité ne pointant aucune page:\n")
print (puissanceIteree (MA1,e,Xo))
    
Xo = creeMatriceAleatoire(16)
print("\nEn ajoutant 2 autorités ne pointant aucune page:\n")
print (puissanceIteree (MA2,e,Xo))
print("\n")



Pour une matrice sans hub ni autorité :

[0.43210734 0.19218274 0.19218274 0.19218274 0.19218274 0.43685781
 0.16082321 0.29752293 0.16082321 0.43210734 0.19218274 0.19218274
 0.19218274 0.19218274]

En ajoutant un hub pointé par aucune page :

[0.43184403 0.19206563 0.19206563 0.19206563 0.19206563 0.43659161
 0.16072521 0.29734163 0.16072521 0.43184403 0.19206563 0.19206563
 0.19206563 0.19206563 0.03490502]

En ajoutant 2 hubs pointés par aucune page :

[0.43163654 0.19197334 0.19197334 0.19197334 0.19197334 0.43638183
 0.16064798 0.29719877 0.16064798 0.43163654 0.19197334 0.19197334
 0.19197334 0.19197334 0.03299939 0.03299939]

En ajoutant 2 hubs pointés par aucune page mais ne pointant pas 8:

[0.43366443 0.1931559  0.1931559  0.1931559  0.1931559  0.43256044
 0.15990048 0.29149747 0.15990048 0.43366443 0.1931559  0.1931559
 0.1931559  0.1931559  0.03302326 0.03302326]

En ajoutant une autorité ne pointant aucune page:

[0.28718958 0.15839185 0.15839185 0.15839185 0.15839185 0.

In [15]:
#Question 3
#accroître le score de certaines pages

Xo = creeMatriceAleatoire(14)

print("\nLa matrice de base :\n")
print (puissanceIteree (M,e,Xo))


La matrice de base :

[0.43210734 0.19218274 0.19218274 0.19218274 0.19218274 0.43685781
 0.16082321 0.29752293 0.16082321 0.43210734 0.19218274 0.19218274
 0.19218274 0.19218274]


In [17]:
print ("7 : ",puissanceIteree (M,e,Xo)[0][6],"\n9 : ",puissanceIteree (M,e,Xo)[0][8])

IndexError: invalid index to scalar variable.

In [ ]:
T = np.array([
 [0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0]],dtype = float)

MT = matriceTransition(transposee(T),stochastique(transposee(T)),a)

print (puissanceIteree (MT,e))
print ("\n7 : ",puissanceIteree (MT,e)[0][6],"\n9 : ",puissanceIteree (MT,e)[0][8])

In [ ]:
#Question 4 
#faire varier le facteur d'amortissement pour analyser son influence.

Xo = creeMatriceAleatoire(len(A))

tab = []

a = 1
P = matriceTransition(transposee(A),stochastique(transposee(A)),a)
print ("\na = 1 :\n",puissanceIteree(P,e,Xo))
tab.append(abs(puissanceIteree(P,e,Xo)[0] - puissanceIteree(P,e,Xo)[1]))

a = 0.75
P = matriceTransition(transposee(A),stochastique(transposee(A)),a)
print ("\na = 0.75 :\n",puissanceIteree(P,e,Xo),"\n")
tab.append(abs(puissanceIteree(P,e,Xo)[0] - puissanceIteree(P,e,Xo)[1]))

a = 0.5
P = matriceTransition(transposee(A),stochastique(transposee(A)),a)
print ("\na = 0.5 :\n",puissanceIteree(P,e,Xo))
tab.append(abs(puissanceIteree(P,e,Xo)[0] - puissanceIteree(P,e,Xo)[1]))

a = 0.25
P = matriceTransition(transposee(A),stochastique(transposee(A)),a)
print ("\na = 0.25 :\n",puissanceIteree(P,e,Xo))
tab.append(abs(puissanceIteree(P,e,Xo)[0] - puissanceIteree(P,e,Xo)[1]))

a = 0.15
P = matriceTransition(transposee(A),stochastique(transposee(A)),a)
print ("\na = 0.15 :\n",puissanceIteree(P,e,Xo))
tab.append(abs(puissanceIteree(P,e,Xo)[0] - puissanceIteree(P,e,Xo)[1]))

a = 0.0
P = matriceTransition(transposee(A),stochastique(transposee(A)),a)
print ("\na = 0 :\n",puissanceIteree(P,e,Xo))
tab.append(abs(puissanceIteree(P,e,Xo)[0] - puissanceIteree(P,e,Xo)[1]))

print(tab)

In [ ]:
plt.plot([1,0.75,0.5,0.25,0.15,0],tab)
plt.show()

## Partie 4 : PageRank - version itérative, analyse des résultats.

In [ ]:
#Question 1
#Premier site choisi : Youtube
Ytb = np.array([
    [1,0,1,0,1,0,0,1,1,0],   #0.86444362
    [1,0,0,0,0,0,0,0,0,0],   #0.09977239
    [1,0,0,0,0,0,0,0,0,0],   #0.24672781
    [1,0,0,0,0,0,0,0,0,0],   #0.03082905
    [1,0,0,0,0,0,0,0,0,0],   #0.22967396
    [1,1,1,0,0,1,0,0,0,0],   #0.03914799
    [1,1,1,0,0,0,0,0,0,0],   #0.03082905
    [1,1,1,0,1,0,0,1,0,0],   #0.30523236
    [1,0,0,0,0,0,0,1,0,0],   #0.17778446
    [1,0,0,0,0,0,0,0,0,0]],  #0.03082905
    dtype = float)

#Deuxième site choisi : AMU
Amu = np.array([
    [1,1,0,1,1,1,1,1,1,1],   #0.47368253
    [1,1,1,0,0,0,0,0,0,0],   #0.47368253
    [1,1,1,0,0,0,0,0,0,0],   #0.281827
    [1,1,1,1,1,1,1,1,1,1],   #0.2596215
    [1,1,0,1,1,1,1,1,1,1],   #0.2596215
    [1,1,0,1,1,1,1,1,1,1],   #0.2596215
    [1,1,0,1,1,1,1,1,1,1],   #0.2596215
    [1,1,0,1,1,1,1,1,1,1],   #0.2596215
    [1,1,0,1,1,1,1,1,1,1],   #0.2596215
    [1,1,0,1,1,1,1,1,1,1]],  #0.2596215
    dtype = float)

#Troisième site choisi : Wikipédia
Wiki = np.array([
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0],   #0.53248714
    [1,1,1,1,1,1,1,1,1,0]],  #0.07298047
    dtype = float)

e = 10e-10

Xo = np.random.rand(10)  #car l'ordre de ces trois matrices est 10.

TYtb = matriceTransition(transposee(Ytb), stochastique(transposee(Ytb)),a)
print(puissanceIteree(stochastique(TYtb), e,Xo))

TAmu = matriceTransition(transposee(Amu), stochastique(transposee(Amu)),a)
print(puissanceIteree(stochastique(TAmu), e,Xo))

TWiki = matriceTransition(transposee(Wiki), stochastique(transposee(Wiki)),a)
print(puissanceIteree(stochastique(TWiki), e,Xo))

In [ ]:
#Question 2 

R = np.array([
    [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]],
    dtype = float)

#Algorithme pour le classement des comptes en fonction de leur nombre d'abonnés.
def classement(R) : 
    nbAbos = []
    for i in range (R.shape[0]) :
        cpt = 0
        for j in range (R.shape[0]) :
            if R[j, i] == 1 :
                cpt += 1
        nbAbos.append((cpt, i))
    nbAbos.sort(reverse=True)
    return nbAbos

print(classement(R))
    
#Appliquer le PageRank
e = 10e-10

Xo = np.random.rand(R.shape[0])

TR = matriceTransition(transposee(R), stochastique(transposee(R)),a)
print(puissanceIteree(stochastique(TR), e,Xo))
#Comparer le classement obtenu avec celui basé uniquement sur le nb d'abos