# SAE 2.02 - Exploitation algorithmique d'un problème

In [30]:
from numpy.random import randint 
import numpy as np
from math import sqrt

def norme(X) :
    return np.sqrt(np.sum(X**2))

A = np.array([
 [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]],dtype = float)

def puissanceIteree (A,e) :
    Xn = Xo.copy()
    XnOld = np.zeros(len(A))
    if (estStochastique(A)) :
        while (norme(Xn - XnOld) > e) :
            XnOld = Xn.copy()
            AXn = A.dot(Xn)
            Xn = AXn.copy()
        return Xn, norme(AXn)
    else :
        while (norme(Xn - XnOld) > e) :
            XnOld = Xn.copy()
            AXn = A.dot(Xn)
            Xn = AXn / norme(AXn)
        return Xn, norme(AXn)

def stochastique(A) :
    for i in range (A.shape[0]):
        temp = 0
        for j in range (A.shape[0]) :
            if (A[j][i] == 1) :
                temp += 1
        for k in range (A.shape[0]) :
            if (A[k][i] == 1) :
                A[k][i] /= temp
    return A

def estStochastique(A) :
    for i in range (A.shape[0]):
        temp = 0
        for j in range (A.shape[0]) :
            temp += A[j][i]
        if (temp != 1):
            return False
    return True

def transposee(A) :
    return A.T

e = 10**(-10)

Q = (stochastique(transposee(A)))

print(Q)

def solutionEquation(V,W) :
    return norme(V - W)

# r est notre vecteur retourné dans l'algorithme ci-dessus
def verification(Q,e) : 
    r = puissanceIteree(Q,e)[0]
    # r est notre vecteur retourné dans l'algorithme ci-dessus
    R = solutionEquation(r, Q.dot(r))
    #R va nous afficher l'écart (sensé tendre vers le nul) entre r et Q*r
    if (R > 1e-5):     #ici, 1e-5 est la marge d'erreur
        return "le vecteur retourné n'est pas solution de l'équation : r = Qr", R
    else : 
        return "le vecteur retourné est solution de l'équation : la norme de r = Qr = ", R

Xo = np.random.rand(len(A))

print (puissanceIteree (Q,e))
print (verification(Q,e))

[[0.         0.5        0.5        0.5        0.5        0.
  0.5        0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.5        0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.5        0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.         0.5        0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.5        0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.         0.         0.
  0.         1.         0.         0.2        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.33333333
  0.         0.         0.         0.         0.         0.
  

## Partie 2 : PageRank - version itérative, deuxième exemple

In [19]:
#B est le graphe d'ordre 5.
B = np.array([
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 1, 0],
 [1, 1, 0, 0, 0],
 [1, 1, 0, 0, 0]], dtype = float)

Q = (transposee(B))

Xo = np.random.rand(len(B))

print(Q)
print('\n')
print(puissanceIteree(Q, e))

[[0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


(array([nan, nan, nan, nan, nan]), 0.0)


/tmp/ipykernel_10819/316187709.py:37: RuntimeWarning: invalid value encountered in divide
  Xn = AXn / norme(AXn)


In [20]:
#Question 2
def matriceTransistion(A,B) :
    a = 0.85
    M = np.zeros((A.shape[0],A.shape[0]))
    for i in range (A.shape[0]):
        for j in range (A.shape[0]) :
            if (sommeTableau(j,A) != 0):    
                M[i][j] = a*B[i][j] + (1-a)/A.shape[0]
            else:
                M[i][j] = 1/A.shape[0]
    return M       

def sommeTableau(j,A) :
    temp = 0
    for i in range (A.shape[0]):
        temp += A[i][j]
    return (temp)

P = matriceTransistion(transposee(B),stochastique(transposee(B)))
print (P,"\n\n\n")
print (puissanceIteree(P,e),"\n")
print(verification(P,e))

[[0.2   0.88  0.455 0.455 0.455]
 [0.2   0.03  0.03  0.455 0.455]
 [0.2   0.03  0.03  0.03  0.03 ]
 [0.2   0.03  0.455 0.03  0.03 ]
 [0.2   0.03  0.03  0.03  0.03 ]] 



(array([0.52950545, 0.25712946, 0.12662577, 0.18044173, 0.12662577]), 0.6411856010515241) 

("le vecteur retourné est solution de l'équation : la norme de r = Qr = ", 7.95568200648268e-12)


## Partie 3 : PageRank - version itérative, analyse des paramètres

In [44]:
 Q = (stochastique(transposee(A)))

Xo = np.random.rand(len(A))

def equation(Q,e) : 
    r = puissanceIteree(Q,e)[0]
    # r est notre vecteur retourné dans l'algorithme ci-dessus
    return solutionEquation(r, Q.dot(r))

e = 1
print("e = ", e, " : ",equation (Q,e),"\n")
e = 10e-2
print("e = ", e, " : ",equation (Q,e),"\n")
e= 10e-4
print("e = ", e, " : ",equation(Q,e),"\n")
e = 10e-6
print("e = ", e, " : ",equation(Q,e),"\n")
e = 10e-8
print("e = ", e, " : ",equation(Q,e),"\n")
e = 10e-10
print("e = ", e, " : ",equation(Q,e),"\n")
e = 10e-20
print("e = ", e, " : ",equation(Q,e),"\n")
e = 10e-100
print("e = ", e, " : ",equation(Q,e),"\n")
e = 10e-10000
print("e = ", e, " : ",equation(Q,e),"\n")

#print ("la différence entre avec e = 1 et e = 10e(-10) = ",norme(puissanceIteree (Q,1)[0]) - norme(puissanceIteree (Q,10**(-10))[0]))

#A faire : analyser les écarts car ils ne sont pas visibles directement avec le print, donc les prints sont à enlever évidemment.

e =  1  :  0.30502286429048553 

e =  0.1  :  0.06053421943021407 

e =  0.001  :  0.0008653162630540167 

e =  1e-05  :  8.989900353173025e-06 

e =  1e-07  :  8.686822496999738e-08 

e =  1e-09  :  9.025052271620057e-10 

e =  1e-19  :  0.0 

e =  1e-99  :  0.0 

e =  0.0  :  0.0 



In [ ]:
#Question 2

#ajout de hubs et d'autorités

C = np.array([
 [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]],dtype = float)



In [ ]:
#Question 3
#accroître le score de certaines pages

In [ ]:
La méthode utilisée : ...
La valider expérimentalement...

In [ ]:
#Question 4 
#faire varier le facteur d'amortissement pour analyser son influence.