# SAE 2.02 - Exploitation algorithmique d'un problème

In [65]:
from numpy.random import randint 
import numpy as np
from math import sqrt

def norme(X) :
    return np.sqrt(np.sum(X**2))

A = np.array([
 [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]],dtype = float)

def puissanceIteree (A,e) :
    Xn = np.random.rand(len(A))
    XnOld = np.zeros(len(A))
    if (estStochastique(A)) :
        while (norme(Xn - XnOld) > e) :
            XnOld = Xn.copy()
            AXn = A.dot(Xn)
            Xn = AXn.copy()
        return Xn, norme(AXn)
    else :
        while (norme(Xn - XnOld) > e) :
            XnOld = Xn.copy()
            AXn = A.dot(Xn)
            Xn = AXn / norme(AXn)
        return Xn, norme(AXn)

def stochastique(A) :
    for i in range (A.shape[0]):
        temp = 0
        for j in range (A.shape[0]) :
            if (A[j][i] == 1) :
                temp += 1
        for k in range (A.shape[0]) :
            if (A[k][i] == 1) :
                A[k][i] /= temp
    return A

def estStochastique(A) :
    for i in range (A.shape[0]):
        temp = 0
        for j in range (A.shape[0]) :
            temp += A[j][i]
        if (temp != 1):
            return False
    return True

def transposee(A) :
    return A.T

e = 10**(-10)

Q = (stochastique(transposee(A)))

print(Q)

# r est notre vecteur retourné dans l'algorithme ci-dessus

def verification(Q,e) : 
    r = puissanceIteree(Q,e)[0]
    # r est notre vecteur retourné dans l'algorithme ci-dessus
    R = norme(r - Q.dot(r))
    #R va nous afficher l'écart (sensé tendre vers le nul) entre r et Q*r
    if (R > 1e-5):     #ici, 1e-5 est la marge d'erreur
        return "le vecteur retourné n'est pas solution de l'équation : r = Qr", R
    else : 
        return "le vecteur retourné est solution de l'équation : la norme de r = Qr = ", R
print (puissanceIteree (Q,e))
print (verification(Q,e))

[[0.         0.5        0.5        0.5        0.5        0.
  0.5        0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.5        0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.5        0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.         0.5        0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.5        0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.         0.         0.
  0.         1.         0.         0.2        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.33333333
  0.         0.         0.         0.         0.         0.
  

## Partie 2 : PageRank - version itérative, deuxième exemple

In [66]:
#B est le graphe d'ordre 5.
B = np.array([
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 1, 0],
 [1, 1, 0, 0, 0],
 [1, 1, 0, 0, 0]], dtype = float)

Q = (transposee(B))

print(Q)
print('\n')
print(puissanceIteree(Q, e))

[[0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


(array([nan, nan, nan, nan, nan]), 0.0)


/tmp/ipykernel_10086/4292137950.py:37: RuntimeWarning: invalid value encountered in divide
  Xn = AXn / norme(AXn)


In [67]:
#Question 2
def matriceTransistion(A,B) :
    a = 0.85
    M = np.zeros((A.shape[0],A.shape[0]))
    for i in range (A.shape[0]):
        for j in range (A.shape[0]) :
            if (sommeTableau(j,A) != 0):    
                M[i][j] = a*B[i][j] + (1-a)/A.shape[0]
            else:
                M[i][j] = 1/A.shape[0]
    return M       

def sommeTableau(j,A) :
    temp = 0
    for i in range (A.shape[0]):
        temp += A[i][j]
    return (temp)

P = matriceTransistion(transposee(B),stochastique(transposee(B)))
print (P,"\n\n\n")
print (puissanceIteree(P,e),"\n")
print(verification(P,e))

[[0.2   0.88  0.455 0.455 0.455]
 [0.2   0.03  0.03  0.455 0.455]
 [0.2   0.03  0.03  0.03  0.03 ]
 [0.2   0.03  0.455 0.03  0.03 ]
 [0.2   0.03  0.03  0.03  0.03 ]] 



(array([1.18557743, 0.57572001, 0.28351862, 0.40401404, 0.28351862]), 1.4356323797102502) 

("le vecteur retourné est solution de l'équation : la norme de r = Qr = ", 1.6018886321409922e-11)


## Partie 3 : PageRank - version itérative, analyse des paramètres

In [68]:
 
Q = (stochastique(transposee(A)))

e = 1
print(puissanceIteree (Q,e),"\n")
e = 10**(-2)
print(puissanceIteree (Q,e),"\n")
e= 10**(-4)
print(puissanceIteree (Q,e),"\n")
e = 10**(-6)
print(puissanceIteree (Q,e),"\n")
e = 10**(-8)
print(puissanceIteree (Q,e),"\n")
e = 10**(-10)
print(puissanceIteree (Q,e),"\n")
e = 10 ** (-20)
print(puissanceIteree (Q,e),"\n")

#A faire : analyser les écarts car ils ne sont pas visibles directement avec le print, donc les prints sont à enlever évidemment.

(array([0.71460671, 0.30494946, 0.33516626, 0.40638364, 0.3857585 ,
       1.05990464, 0.33047005, 0.55937476, 0.33047005, 0.72682065,
       0.2873909 , 0.45559282, 0.21242574, 0.21049544]), 1.8953968299759516) 

(array([1.0814955 , 0.43610043, 0.43615533, 0.43613609, 0.43614994,
       1.23204691, 0.40949743, 0.81796856, 0.40949743, 1.02114506,
       0.40808123, 0.40806338, 0.40804307, 0.40809034]), 2.482276693558168) 

(array([0.89642413, 0.35852537, 0.35852537, 0.35852537, 0.35852537,
       1.07652605, 0.35884201, 0.71768403, 0.35884201, 0.89778599,
       0.35915869, 0.35915869, 0.35915869, 0.35915869]), 2.1380485055140954) 

(array([0.74248064, 0.29699268, 0.29699268, 0.29699268, 0.29699268,
       0.89096892, 0.29698964, 0.59397928, 0.29698964, 0.74246755,
       0.29698659, 0.29698659, 0.29698659, 0.29698659]), 1.7695199960707402) 

(array([0.81536566, 0.32614626, 0.32614626, 0.32614626, 0.32614626,
       0.97843887, 0.32614629, 0.65229258, 0.32614629, 0.81536579,
       0.3