# SAE 2.02 - Exploitation algorithmique d'un problème

In [51]:
from numpy.random import randint 
import numpy as np
from math import sqrt

def norme(X) :
    return np.sqrt(np.sum(X**2))

A = np.array([
 [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]],dtype = float)

def puissanceIteree (A,e) :
    Xn = np.random.rand(len(A))
    XnOld = np.zeros(len(A))
    if (estStochastique(A)) :
        while (norme(Xn - XnOld) > e) :
            XnOld = Xn.copy()
            AXn = A.dot(Xn)
            Xn = AXn.copy()
        return Xn, norme(AXn)
    else :
        while (norme(Xn - XnOld) > e) :
            XnOld = Xn.copy()
            AXn = A.dot(Xn)
            Xn = AXn / norme(AXn)
        return Xn, norme(AXn)

def stochastique(A) :
    for i in range (A.shape[0]):
        temp = 0
        for j in range (A.shape[0]) :
            if (A[j][i] == 1) :
                temp += 1
        for k in range (A.shape[0]) :
            if (A[k][i] == 1) :
                A[k][i] /= temp
    return A

def estStochastique(A) :
    for i in range (A.shape[0]):
        temp = 0
        for j in range (A.shape[0]) :
            temp += A[j][i]
        if (temp != 1):
            return False
    return True

def transposee(A) :
    return A.T

e = 10**(-10)

Q = (stochastique(transposee(A)))

print(Q)

# r est notre vecteur retourné dans l'algorithme ci-dessus

def verification(Q,e) : 
    r = puissanceIteree(Q,e)[0]
    # r est notre vecteur retourné dans l'algorithme ci-dessus
    R = norme(r - Q.dot(r))
    #R va nous afficher l'écart (sensé tendre vers le nul) entre r et Q*r
    if (R > 1e-5):     #ici, 1e-5 est la marge d'erreur
        return "le vecteur retourné n'est pas solution de l'équation : r = Qr", R
    else : 
        return "le vecteur retourné est solution de l'équation : la norme de r = Qr = ", R
print (puissanceIteree (Q,e))
print (verification(Q,e))

[[0.         0.5        0.5        0.5        0.5        0.
  0.5        0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.5        0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.5        0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.         0.5        0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.5        0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.         0.         0.         0.         0.
  0.         1.         0.         0.2        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.33333333
  0.         0.         0.         0.         0.         0.
  

## Partie 2 : PageRank - version itérative, deuxième exemple

In [46]:
from numpy.random import randint 
import numpy as np
from math import sqrt

#B est le graphe d'ordre 5.
B = np.array([
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 1, 0],
 [1, 1, 0, 0, 0],
 [1, 1, 0, 0, 0]], dtype = float)

Q = (transposee(B))

print(Q)
print('\n')
print(puissanceIteree(Q, e))

[[0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


(array([nan, nan, nan, nan, nan]), 0.0)


/tmp/ipykernel_10086/4153716820.py:44: RuntimeWarning: invalid value encountered in divide
  Xn = AXn / norme(AXn)


In [49]:
#Question 2
from numpy.random import randint 
import numpy as np
from math import sqrt
  
def matriceTransistion(A,B) :
    a = 0.85
    M = np.zeros((A.shape[0],A.shape[0]))
    for i in range (A.shape[0]):
        for j in range (A.shape[0]) :
            if (sommeTableau(j,A) != 0):    
                M[i][j] = a*B[i][j] + (1-a)/A.shape[0]
            else:
                M[i][j] = 1/A.shape[0]
    return M       

def sommeTableau(j,A) :
    temp = 0
    for i in range (A.shape[0]):
        temp += A[i][j]
    return (temp)

P = matriceTransistion(transposee(B),stochastique(transposee(B)))
print (P,"\n\n\n")
print (puissanceIteree(P,e),"\n")
print(verification(P))

[[0.2   0.88  0.455 0.455 0.455]
 [0.2   0.03  0.03  0.455 0.455]
 [0.2   0.03  0.03  0.03  0.03 ]
 [0.2   0.03  0.455 0.03  0.03 ]
 [0.2   0.03  0.03  0.03  0.03 ]] 



(array([1.20129932, 0.58335461, 0.28727835, 0.40937165, 0.28727835]), 1.4546702427716014) 

("le vecteur retourné est solution de l'équation : r = Qr", 2.5088948171112993e-11)


## Partie 3 : PageRank - version itérative, analyse des paramètres

In [60]:
from numpy.random import randint 
import numpy as np
from math import sqrt
    
Q = (stochastique(transposee(A)))

e = 1
print(puissanceIteree (Q,e),"\n")
e = 1**(-2)
print(puissanceIteree (Q,e),"\n")
e= 1**(-4)
print(puissanceIteree (Q,e),"\n")
e = 1**(-6)
print(puissanceIteree (Q,e),"\n")
e = 1**(-8)
print(puissanceIteree (Q,e),"\n")
e = 1**(-10)
print(puissanceIteree (Q,e),"\n")
e = 1 ** (-20)
print(puissanceIteree (Q,e),"\n")

(array([0.81398313, 0.34054744, 0.32394235, 0.32987977, 0.32930399,
       0.6022471 , 0.34098073, 0.44801718, 0.34098073, 1.13662197,
       0.51996839, 0.41449786, 0.51013991, 0.52439016]), 2.041080857467327) 

(array([0.87552538, 0.38897579, 0.40170356, 0.52261043, 0.39467931,
       1.2282056 , 0.33937305, 0.45928241, 0.33937305, 0.55495029,
       0.26092206, 0.26000698, 0.28779776, 0.33430161]), 2.0238879378980017) 

(array([0.9842928 , 0.44058052, 0.33246017, 0.36149447, 0.34756365,
       0.76579777, 0.47971956, 0.76639279, 0.47971956, 0.82730556,
       0.30337477, 0.32611805, 0.29596932, 0.2580195 ]), 2.048417314285515) 

(array([0.91200039, 0.33035913, 0.33565479, 0.34591926, 0.34807313,
       0.90366748, 0.13105711, 0.60580662, 0.13105711, 1.11604772,
       0.41674617, 0.45237631, 0.45726783, 0.45131217]), 2.1328362076968204) 

(array([0.72278741, 0.25790001, 0.25183418, 0.24134682, 0.33284406,
       1.00109621, 0.10945957, 0.38525931, 0.10945957, 0.85793969,
       0.46